name: WGCustomFlags
description: API for Bukkit plugin writers that allows you to add custom flags to WorldGuard regions.
authors: [ mewin ]
version: "${project.version}"
website: http://dev.bukkit.org/server-mods/worldguard-custom-flags/

main: com.mewin.WGCustomFlags.WGCustomFlagsPlugin
depend: [ WorldGuard ]
softdepend: [ WorldEdit ]
load: STARTUP


commands:
  flags:
    description: allows you to display information about WorldGuard flags
    usage: /<command> [-d|i <flag>]
    permission: wgcustomflags.flags
permissions:
  wgcustomflags.flags:
    default: op
